/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class camera_coord_t implements lcm.lcm.LCMEncodable
{
    public double x;
    public double y;
    public double z;
    public double v_x;
    public double v_y;
    public double v_z;
    public long mode;
    public long utime;
 
    public camera_coord_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xe7a63d3acc61be77L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.camera_coord_t.class))
            return 0L;
 
        classes.add(lcmtypes.camera_coord_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeDouble(this.x); 
 
        outs.writeDouble(this.y); 
 
        outs.writeDouble(this.z); 
 
        outs.writeDouble(this.v_x); 
 
        outs.writeDouble(this.v_y); 
 
        outs.writeDouble(this.v_z); 
 
        outs.writeLong(this.mode); 
 
        outs.writeLong(this.utime); 
 
    }
 
    public camera_coord_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public camera_coord_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.camera_coord_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.camera_coord_t o = new lcmtypes.camera_coord_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.x = ins.readDouble();
 
        this.y = ins.readDouble();
 
        this.z = ins.readDouble();
 
        this.v_x = ins.readDouble();
 
        this.v_y = ins.readDouble();
 
        this.v_z = ins.readDouble();
 
        this.mode = ins.readLong();
 
        this.utime = ins.readLong();
 
    }
 
    public lcmtypes.camera_coord_t copy()
    {
        lcmtypes.camera_coord_t outobj = new lcmtypes.camera_coord_t();
        outobj.x = this.x;
 
        outobj.y = this.y;
 
        outobj.z = this.z;
 
        outobj.v_x = this.v_x;
 
        outobj.v_y = this.v_y;
 
        outobj.v_z = this.v_z;
 
        outobj.mode = this.mode;
 
        outobj.utime = this.utime;
 
        return outobj;
    }
 
}

